name: CI
on:
  push: null
  release:
    types:
      - created
jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu, ghc: 9.4.2 }
          - { os: ubuntu, ghc: 9.2.3 }
          - { os: ubuntu, ghc: 9.0.2 }
          - { os: ubuntu, ghc: 8.10.7 }
          - { os: macos, ghc: 8.10.7 }
          - { os: windows, ghc: 8.10.7 }
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal freeze && cat cabal.project.freeze
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal build
      - run: cabal sdist
      - uses: actions/upload-artifact@v2
        with:
          path: dist-newstyle/sdist/splint-*.tar.gz
          name: splint-${{ github.sha }}.tar.gz
      - run: cabal check
      - if: github.event_name == 'release' && matrix.os == 'ubuntu' && matrix.ghc == '9.0.2'
        run: cabal upload --publish --username '${{ secrets.HACKAGE_USERNAME }}' --password '${{ secrets.HACKAGE_PASSWORD }}' dist-newstyle/sdist/splint-*.tar.gz
